<div class="col-sm-3 col-md-2 sidebar">
  <ul class="nav nav-sidebar">
    <li class="active"><a href="">Lista firm <span class="sr-only">(current)</span></a></li>
    <li><a href="companies/search">Wyszukaj firmę</a></li>
    <li><a href="index/sync">Sync MySQL -> ElasticSearch</a></li>
  </ul>
</div>
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
  <h1 class="page-header text-center">Test ElasticSearch</h1>
  <center>
    <h2 class="page-header text-center"><?php if(empty($companies)){echo 'Sync data.';}?></h2>
  </center>

  <?php
  foreach($companies as $company)
  {

    echo "<br>".$company['_source']['id'].' - '.$company['_source']['CompanyName']."<br>".
        implode(',',$company['_source']['CompanyCategory'])."<br>";
  }
  ?>
</div>